/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jogodaforca;

import java.awt.Color;
import java.awt.Component;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Augus
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
    public Jogo() {
        initComponents();
    }
    private int quantidadeDeErros = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PalavraSecreta = new javax.swing.JTextField();
        BotaoIniciarJogo = new javax.swing.JButton();
        BotaoSalvarPalavra = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Chute = new javax.swing.JTextField();
        BotaoChutar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelPalavraSecreta = new javax.swing.JLabel();
        erro1 = new javax.swing.JLabel();
        erro2 = new javax.swing.JLabel();
        erro3 = new javax.swing.JLabel();
        erro4 = new javax.swing.JLabel();
        erro5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogo da forca");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jogo da Forca");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("informe uma palavra secreta");

        PalavraSecreta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalavraSecretaActionPerformed(evt);
            }
        });

        BotaoIniciarJogo.setText("Iniciar jogo");
        BotaoIniciarJogo.setEnabled(false);
        BotaoIniciarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoIniciarJogoActionPerformed(evt);
            }
        });

        BotaoSalvarPalavra.setText("Salvar");
        BotaoSalvarPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarPalavraActionPerformed(evt);
            }
        });

        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Informe uma letra");

        Chute.setEditable(false);

        BotaoChutar.setText("Chutar");
        BotaoChutar.setEnabled(false);
        BotaoChutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoChutarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Acertos/Erros");

        labelPalavraSecreta.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        labelPalavraSecreta.setText(" ");

        erro1.setBackground(java.awt.Color.green);
        erro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erro1.setText("1");
        erro1.setToolTipText("");
        erro1.setAutoscrolls(true);
        erro1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        erro1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        erro1.setMaximumSize(new java.awt.Dimension(50, 50));
        erro1.setMinimumSize(new java.awt.Dimension(50, 50));
        erro1.setName("erro1"); // NOI18N
        erro1.setOpaque(true);
        erro1.setPreferredSize(new java.awt.Dimension(50, 50));

        erro2.setBackground(java.awt.Color.green);
        erro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erro2.setText("2");
        erro2.setToolTipText("");
        erro2.setAutoscrolls(true);
        erro2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        erro2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        erro2.setMaximumSize(new java.awt.Dimension(50, 50));
        erro2.setMinimumSize(new java.awt.Dimension(50, 50));
        erro2.setName("erro2"); // NOI18N
        erro2.setOpaque(true);
        erro2.setPreferredSize(new java.awt.Dimension(50, 50));

        erro3.setBackground(java.awt.Color.green);
        erro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erro3.setText("3");
        erro3.setToolTipText("");
        erro3.setAutoscrolls(true);
        erro3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        erro3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        erro3.setMaximumSize(new java.awt.Dimension(50, 50));
        erro3.setMinimumSize(new java.awt.Dimension(50, 50));
        erro3.setName("erro3"); // NOI18N
        erro3.setOpaque(true);
        erro3.setPreferredSize(new java.awt.Dimension(50, 50));

        erro4.setBackground(java.awt.Color.green);
        erro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erro4.setText("4");
        erro4.setToolTipText("");
        erro4.setAutoscrolls(true);
        erro4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        erro4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        erro4.setMaximumSize(new java.awt.Dimension(50, 50));
        erro4.setMinimumSize(new java.awt.Dimension(50, 50));
        erro4.setName("erro4"); // NOI18N
        erro4.setOpaque(true);
        erro4.setPreferredSize(new java.awt.Dimension(50, 50));

        erro5.setBackground(java.awt.Color.green);
        erro5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        erro5.setText("5");
        erro5.setToolTipText("");
        erro5.setAutoscrolls(true);
        erro5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        erro5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        erro5.setMaximumSize(new java.awt.Dimension(50, 50));
        erro5.setMinimumSize(new java.awt.Dimension(50, 50));
        erro5.setName("erro5"); // NOI18N
        erro5.setOpaque(true);
        erro5.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(BotaoIniciarJogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PalavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(BotaoSalvarPalavra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPalavraSecreta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(110, 110, 110))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Chute, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotaoChutar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(erro1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(erro2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(erro3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(erro4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(erro5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BotaoSalvarPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PalavraSecreta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BotaoIniciarJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(Chute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotaoChutar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(erro1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(erro5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPalavraSecreta)
                        .addGap(42, 42, 42))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PalavraSecretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalavraSecretaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PalavraSecretaActionPerformed

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BotaoSairActionPerformed

    private void BotaoSalvarPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarPalavraActionPerformed
        // TODO add your handling code here:
        String palavraSecreta = PalavraSecreta.getText();
        String palavraSecretaEscondida = "";
        for (int i = 0; i < palavraSecreta.length(); i++) {
            palavraSecretaEscondida += "_ ";
        }
        labelPalavraSecreta.setText(palavraSecretaEscondida);
        BotaoIniciarJogo.setEnabled(true);
    }//GEN-LAST:event_BotaoSalvarPalavraActionPerformed

    private void BotaoChutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoChutarActionPerformed
        // TODO add your handling code here:
        char chute = Chute.getText().charAt(0);
        String palavraSecreta = PalavraSecreta.getText();
        String labelPalavra = labelPalavraSecreta.getText();
        int errosPermitidos = 5;
        boolean encontrouLetra = false;
        
       var componentesComErro = new ArrayList<>();
       Component[] componentes = getContentPane().getComponents();
         for (Component componente : componentes) {
            if (componente.getName() != null && componente.getName().contains("erro")) {
                componentesComErro.add(componente);
            }
        }
            for (int i = 0; i < palavraSecreta.length(); i++) {
                if (palavraSecreta.charAt(i) == chute) {
                    labelPalavra = labelPalavra.substring(0, i * 2) + chute + " " + labelPalavra.substring((i * 2) + 2);
                    labelPalavraSecreta.setText(labelPalavra);
                    encontrouLetra = true;
                }
            }
            if (encontrouLetra) {
                if (labelPalavra.indexOf("_") == -1) {
                    JOptionPane.showMessageDialog(this, "Você Ganhou");
                    ResetarJogo();
                }
            }else{
                    // modificar que errou a letra
                    Component componenteParaFicarVermelho = (Component) componentesComErro.get(quantidadeDeErros);
                    componenteParaFicarVermelho.setBackground(Color.red);
                    quantidadeDeErros ++;
                    if(quantidadeDeErros == errosPermitidos){
                       JOptionPane.showMessageDialog(this, "Você Perdeu, a palavra era " + palavraSecreta);
                       ResetarJogo();
                    } 
                }
    }//GEN-LAST:event_BotaoChutarActionPerformed

    private void ResetarJogo(){
        labelPalavraSecreta.setText(" ");
        BotaoIniciarJogo.setEnabled(false);
        PalavraSecreta.setForeground(Color.black);
        PalavraSecreta.setEditable(true);
        PalavraSecreta.setText("");
        PalavraSecreta.setFocusable(true);
        BotaoSalvarPalavra.setEnabled(true);
        BotaoChutar.setEnabled(false);
        Chute.setEditable(false);
        Chute.setText("");
        quantidadeDeErros = 0;
        
       var componentesComErro = new ArrayList<>();
       Component[] componentes = getContentPane().getComponents();
         for (Component componente : componentes) {
            if (componente.getName() != null && componente.getName().contains("erro")) {
                componente.setBackground(Color.green);
         
            }
        }
        
    }
    
    private void BotaoIniciarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoIniciarJogoActionPerformed
        // TODO add your handling code here:
        PalavraSecreta.setForeground(Color.white);
        PalavraSecreta.setEditable(false);
        PalavraSecreta.setFocusable(false);
        BotaoSalvarPalavra.setEnabled(false);
        BotaoChutar.setEnabled(true);
        Chute.setEditable(true);
    }//GEN-LAST:event_BotaoIniciarJogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoChutar;
    private javax.swing.JButton BotaoIniciarJogo;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BotaoSalvarPalavra;
    private javax.swing.JTextField Chute;
    private javax.swing.JTextField PalavraSecreta;
    private javax.swing.JLabel erro1;
    private javax.swing.JLabel erro2;
    private javax.swing.JLabel erro3;
    private javax.swing.JLabel erro4;
    private javax.swing.JLabel erro5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelPalavraSecreta;
    // End of variables declaration//GEN-END:variables
}
